app:
  mode: 'debug'
  port: 8000
db:
  user: 'dev'
  password: 'admin@dev'
  host: 'localhost'
  port: 3306
  name: 'appdb'
cors:
  client: 
    - 'http://localhost:8080'
secret:
  token: huhfcd28tPEWdBNb04v/+A+jj0dV6i5EGNY/TDYeb4u7I9Jovx4ztyZ/eGpeq+GTLns0rC0vcfxQidFk47zIXA==

